### ISSUE TITLE
userEvent.typeで空文字をtypeするとエラーになる部分がある

### ISSUE THREAD

**Issue by maiko-ando** [s-sasaki-0529/zenn#3]
https://github.com/s-sasaki-0529/zenn/blob/27d7478e1a67b1ce02064c3f0adff41cdf73cdda/books/storybook-7-with-vue-3/play_function.md?plain=1#L234

当該の行についてですが、`userEvent.type` は第2引数に空文字を取る場合に以下のエラーとなります

```
userEvent.type(within(<div#storybook-root>).getByLabelText("Name", { selector: "input" }), "")
Expected key descriptor but found "" in ""
    See https://testing-library.com/docs/user-event/keyboard
    for more information about how userEvent parses your input.
```
<img width="720" alt="スクリーンショット 2023-10-11 15 15 23" src="https://github.com/s-sasaki-0529/zenn/assets/13215919/b64cd56e-4f21-421b-827a-6add3d54f51b">

明示的に空を入力する代替として、 `await userEvent.clear(nameInput);` か、もしくは行削除で良いのではないかと思います。
ご一考いただけますと幸いです。

ーーー
また、素晴らしい書籍を公開くださりありがとうございます。本当に勉強になりました、心よりの感謝を伝えさせていただければと思います。

**Comment by s-sasaki-0529** [comment]
@maiko-ando 
ご返信が遅くなってしまい申し訳有りません！
また、詳細な誤りについてのご報告ありがとうございます！！

仰る通り、該当箇所は現状ではエラーが発生することが確認できました。
こちらは本書内にて、 `@storybook/testing-library` のバージョンを固定せずにインストールしていたため、執筆当初と現在のバージョンで仕様が変わったことが原因と思われます。

本来は `Storybook` とあわせてバージョンを固定するべきでしたが、取り急ぎ最新バージョンでも通るようにご提案いただいた修正を適用いたします！
